# This is a basic workflow to help you get started with Actions

name: Deploy ishikawa Virtual Machine

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: Resource Group Name
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-virtual-machine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, ${{ github.event.inputs.resourceGroupName }} 
